#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  repository: linuxserver/jackett
  pullPolicy: IfNotPresent
  tag: version-v0.17.591

strategy:
  type: Recreate

env:
  TZ: "America/Chicago"
  PUID: 1001
  PGID: 1001

service:
  port:
    port: 9117

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    #cert-manager.io/cluster-issuer: "letsencrypt-prod"
  labels:
    ingressClassName: "nginx"
  hosts:
    - host: jackett.sweet-toast.com
      paths:
        - path: /
          pathType: Prefix
  # tls:
  #   - secretName: jackett-tls
  #     hosts:
  #      - jackett.sweet-toast.com 

persistence:
  config:
    enabled: true
    mountPath: /config
    existingClaim: jackett-config

  torrentblackhole:
    enabled: false
    emptyDir:
      enabled: false
    mountPath: /downloads
