#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  repository: linuxserver/radarr
  pullPolicy: IfNotPresent
  tag: version-3.0.2.4552

strategy:
  type: Recreate

env:
  TZ: "America/Chicago"
  PUID: 1001
  PGID: 1001

service:
  port:
    port: 7878

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  labels:
    ingressClassName: "nginx"
  hosts:
    - host: radarr.sweet-toast.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: radarr-tls
      hosts:
       - radarr.sweet-toast.com 

initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c', "cp -a /backup/radarr/config/. /config/"]
    volumeMounts:
      - mountPath: /backup
        name: backup
      - mountPath: /config
        name: config

probes:
  liveness:
    enabled: true
    ## Set this to true if you wish to specify your own livenessProbe
    custom: true
    ## The spec field contains the values for the default livenessProbe.
    ## If you selected custom: true, this field holds the definition of the livenessProbe.
    spec:
      exec:
        command:
        - /usr/bin/env
        - bash
        - -c
        - curl --fail localhost:7878/api/v3/system/status?apiKey=`IFS=\> && while
          read -d \< E C; do if [[ $E = "ApiKey" ]]; then echo $C; fi; done < /config/config.xml`
      failureThreshold: 5
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10

persistence:
  config:
    enabled: true
    mountPath: /config
    existingClaim: radarr-config

  backup:
    enabled: true
    mountPath: /backup
    existingClaim: config-backup

  media:
    enabled: true
    mountPath: /media
    existingClaim: media

  completed:
    enabled: true
    mountPath: /completed
    existingClaim: completed

# Enable gathering Prometheus metrics
prometheus:
  podMonitor:
    enabled: false
